# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and push Docker image
  jobs:  
  - job: Build Docker image
    displayName: Build Docker image
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'andreibirsan docker hub'
        repository: 'andreibirsan/todowebapp'
        command: 'build'
        Dockerfile: '**/Application/Dockerfile'
        tags: |
          $(tag)
  - job: Push Docker image
    displayName: Push Docker image
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'andreibirsan docker hub'
        repository: 'andreibirsan/todowebapp'
        command: 'push'
        tags: |
          $(tag)
          
- stage: Terraforming
  displayName: 'Terraforming to Azure'
  dependsOn: Build
  jobs:
  - job: Provision
    displayName: 'Terraforming to Azure'
    pool:
      vmImage: 'ubuntu-latest'
    variables: 
    - group: 'Terraform Service Principal variables'
    steps:
    - script: |
        set -e
        cd Infrastructure

        terraform init -input=false
        terraform apply -input=false -auto-approve
      name: 'RunTerraform'
      displayName: 'Terraform apply'
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        TF_VAR_imagebuild: $(tag)
    - task: AzureCLI@2
      displayName: 'Create service connectors'
      inputs:
        azureSubscription: 'Azure'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: 'Infrastructure/Create service connectors.sh'
